apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: shop-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shop-app
  template:
    metadata:
      labels:
        app: shop-app
    spec:
      containers:
      - name: backend-container
        image: estheruge/backend-service:v1.0.0
        ports:
        - containerPort: 5000
        env:
        - name: MONGODB_URL
          value: "mongodb://mongo:27017/yolomy"  # MongoDB service URL
