apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-statefulset
  labels:
    app: shop-app
    component: mongo
spec:
  serviceName: mongo-headless  # Headless Service for StatefulSet
  replicas: 3  # Number of MongoDB instances
  selector:
    matchLabels:
      app: shop-app
      component: mongo
  template:
    metadata:
      labels:
        app: shop-app
        component: mongo
    spec:
      containers:
      - name: mongo-container
        image: mongo:latest
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongo-data
          mountPath: /data/db
      volumes:
      - name: mongo-data
        emptyDir: {}  # In a real setup, use PersistentVolumeClaim for persistent storage
  volumeClaimTemplates:
  - metadata:
      name: mongo-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi
