apiVersion: v1
kind: Service
metadata:
  name: backend-service
  labels:
    app: shop-app
    component: backend
spec:
  type: ClusterIP
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: shop-app
    component: backend
