apiVersion: v1
kind: Service
metadata:
  name: mongo-headless
  labels:
    app: shop-app
    component: mongo
spec:
  clusterIP: None
  selector:
    app: shop-app
    component: mongo
  ports:
    - port: 27017
